version: '3.8'

services:
  flask-app:
    build:
      context: .  # Make sure the build context is set to the current directory
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile name
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"  # Expose port 80 on localhost for Nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount custom config
    depends_on:
      - flask-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

